### ISSUE TITLE
Missing HPG 2016 demo

### ISSUE THREAD

**Issue by speps** [abasilak/abasilak.github.io#1]
This link is broken :

http://kostasvardis.com/files/research/hpg2016-demo.7z

Thanks.

**Comment by abasilak** [comment]
Unfortunately, there is no available demo for this paper. 
However, you can download the source code (GLSL 4.4 shaders) from [here](http://kostasvardis.com/files/research/dirt_hpg2016_shader_source.zip)

Thanks for noting (I removed the link).

**Comment by abasilak** [comment]
Hi again,

The demo is ready!!! You can found it [here](http://graphics.cs.aueb.gr/graphics/downloads.html)

Thanks

**Comment by speps** [comment]
Thanks a lot Andreas! I'll have to try that at work as I don't have a
Maxwell at home :)

Remi.
